### ISSUE TITLE
Impossible to save Rest Service in 1.10.2 - Problem with page size parameter

### ISSUE THREAD

**Issue by ppaulis** [laminas-api-tools/api-tools-admin#75]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 1.10.2

#### Summary

After upgrading from 1.9.0 to 1.10.2, I can no longer save the General Settings of a REST Service.

#### Current behavior

The PATCH request to `/api-tools/api/module/tms/rest/tms-V1-Rest-xxxxxxxxxx-Controller` fails with a 422 error, saying:
```
page_size: ["The Page Size must be either a positive integer or the value "-1" (disabling pagination)"]
```
The related fields from the request body are:
```
page_size: "50"
page_size_param: null
```
When switching back to 1.9.0, the problem disappears.

**Comment by weierophinney** [comment]
Fixed with #77
