### ISSUE TITLE
Update laminas-api-tools/api-tools-mvc-auth to version ^1.7 for PHP 8.1 support

### ISSUE THREAD

**Issue by dstockto** [laminas-api-tools/api-tools-admin#89]
### Feature Request

This library says it is supporting PHP 8.1, but it requires laminas-api-tools/api-tools-mvc-auth ^1.5 which is only supporting PHP 8.0. Please update composer.json to require ^1.7 which does support PHP 8.1.

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | yes/no
| BC Break    | yes/no

#### Summary

In order to use this library on PHP 8.1, it needs to support dependencies which also support PHP 8.1. Currently it is requesting a version that is not supported in PHP 8.1. Please update the composer.json file to require laminas-api-tools/api-tools-mvc-auth ^1.7 so this library can be used with PHP 8.1.

Thank you

**Comment by Ocramius** [comment]
`^1.5` also includes `^1.7`

**Comment by froschdesign** [comment]
@dstockto 
See also in the documentation of Composer:

- [Writing Version Constraints](https://getcomposer.org/doc/articles/versions.md#writing-version-constraints)
- [Caret Version Range (^)](https://getcomposer.org/doc/articles/versions.md#caret-version-range-)

**Comment by dstockto** [comment]
Apologies for the confusion - this ticket came because composer is indicating it cannot figure out an installable set of packages and for some reason it is limiting it to 1.6 of the api-tools-mvc-auth package. I'm not yet sure what's holding it back, but this one was the indicating the initial problem.
